import { Provider } from "./types";

export type ExtendedProvider = Provider & {
  description: string;
  rating: number;
  reviews: number;
  emoji: string;
  tags: string[];
  availableToday: boolean;
  slots: string[];
  passportDiscount: number; // % off with passport stamps
  distance: string;
  hours: string;
  phone: string;
};

export type WellnessPackage = {
  id: string;
  title: string;
  subtitle: string;
  emoji: string;
  providerIds: string[];
  providerNames: string[];
  originalEtb: number;
  discountPct: number;
  finalEtb: number;
  bestFor: string;
};

export const extendedProviders: ExtendedProvider[] = [
  {
    id: "bole-yoga",
    name: "Bole Reset Yoga",
    type: "Beginner yoga",
    area: "Bole",
    price: "350 ETB",
    bestFor: "High stress, low sleep",
    category: "Stress",
    emoji: "🧘",
    description: "Small-group beginner yoga classes led by certified instructors. Focuses on breath, posture correction, and stress release. No experience needed — classes run in Amharic and English.",
    rating: 4.8,
    reviews: 142,
    tags: ["beginner-friendly", "bilingual", "small groups"],
    availableToday: true,
    slots: ["07:00 AM", "10:00 AM", "06:00 PM", "07:30 PM"],
    passportDiscount: 20,
    distance: "~10 min from Bole Road",
    hours: "Mon–Sat 6:30 AM – 8:00 PM",
    phone: "+251 91 234 5670",
  },
  {
    id: "bole-meditation",
    name: "Bole Mindfulness Studio",
    type: "Guided meditation",
    area: "Bole",
    price: "280 ETB",
    bestFor: "Anxiety, burnout, and racing thoughts",
    category: "Stress",
    emoji: "🌿",
    description: "30–45 minute guided meditation sessions for urban professionals. Covers breath-focus, body scan, and loving-kindness techniques. Private and small-group options available.",
    rating: 4.7,
    reviews: 89,
    tags: ["burnout relief", "anxiety", "private sessions"],
    availableToday: true,
    slots: ["08:00 AM", "12:00 PM", "05:00 PM", "07:00 PM"],
    passportDiscount: 15,
    distance: "~8 min from Bole Airport Road",
    hours: "Mon–Sun 7:00 AM – 9:00 PM",
    phone: "+251 91 345 6781",
  },
  {
    id: "lideta-massage",
    name: "Lideta Recovery Spa",
    type: "Massage & recovery",
    area: "Lideta",
    price: "900 ETB",
    bestFor: "Muscle tension and burnout",
    category: "Recovery",
    emoji: "💆",
    description: "Professional therapeutic massage and recovery spa. Offers Swedish, deep tissue, and traditional Ethiopian massage. Quiet environment designed for full nervous system reset.",
    rating: 4.9,
    reviews: 218,
    tags: ["deep tissue", "ethiopian massage", "couples option"],
    availableToday: false,
    slots: ["10:00 AM", "02:00 PM", "04:00 PM"],
    passportDiscount: 20,
    distance: "~20 min from Bole",
    hours: "Tue–Sun 9:00 AM – 7:00 PM",
    phone: "+251 91 456 7892",
  },
  {
    id: "entoto-retreat",
    name: "Entoto Weekend Reset",
    type: "Wellness retreat",
    area: "Entoto",
    price: "1,800 ETB",
    bestFor: "Sleep debt and social reset",
    category: "Recovery",
    emoji: "🏔️",
    description: "Full-day and weekend wellness retreats in the Entoto mountains. Includes guided nature walks, group breathwork, healthy local food, and facilitated reflection. Perfect for burning out urban workers.",
    rating: 4.9,
    reviews: 76,
    tags: ["full day", "nature", "group retreat", "includes meals"],
    availableToday: false,
    slots: ["Saturday 7:00 AM", "Sunday 7:00 AM"],
    passportDiscount: 15,
    distance: "~40 min from Bole",
    hours: "Weekends only — advance booking required",
    phone: "+251 91 567 8903",
  },
  {
    id: "meskel-walk",
    name: "Meskel Walk Club",
    type: "Guided group walk",
    area: "Meskel Square",
    price: "Free",
    bestFor: "Low movement days",
    category: "Movement",
    emoji: "🚶",
    description: "Free community walking club that meets at Meskel Square. Guided routes of 30–60 minutes through the city. Welcoming to all fitness levels. A great first step for beginners.",
    rating: 4.6,
    reviews: 304,
    tags: ["free", "community", "all levels", "outdoor"],
    availableToday: true,
    slots: ["06:30 AM", "06:00 PM"],
    passportDiscount: 0,
    distance: "Meskel Square — central",
    hours: "Daily 6:30 AM and 6:00 PM",
    phone: "+251 91 678 9014",
  },
  {
    id: "piazza-gym",
    name: "Piazza Fitness Center",
    type: "Gym",
    area: "Piazza",
    price: "400 ETB / month",
    bestFor: "Building consistent movement habits",
    category: "Movement",
    emoji: "🏋️",
    description: "Well-equipped gym with cardio machines, free weights, and group classes. Personal trainers available for custom programs. Day passes available without monthly commitment.",
    rating: 4.4,
    reviews: 167,
    tags: ["day pass available", "personal trainer", "group classes"],
    availableToday: true,
    slots: ["Open access — 6:00 AM to 10:00 PM"],
    passportDiscount: 10,
    distance: "~15 min from Meskel Square",
    hours: "Mon–Sat 6:00 AM – 10:00 PM, Sun 8:00 AM – 6:00 PM",
    phone: "+251 91 789 0125",
  },
  {
    id: "kazanchis-nutrition",
    name: "Kazanchis Nutrition Desk",
    type: "Nutritionist",
    area: "Kazanchis",
    price: "500 ETB",
    bestFor: "BP and glucose lifestyle habits",
    category: "Food",
    emoji: "🥗",
    description: "One-on-one nutrition consultations with a registered dietitian. Specialises in lifestyle diseases — hypertension, type 2 diabetes, and weight management using Ethiopian food culture.",
    rating: 4.8,
    reviews: 93,
    tags: ["BP specialist", "diabetes", "ethiopian food plans"],
    availableToday: false,
    slots: ["09:00 AM", "11:00 AM", "03:00 PM"],
    passportDiscount: 20,
    distance: "~18 min from Bole",
    hours: "Mon–Fri 8:00 AM – 6:00 PM",
    phone: "+251 91 890 1236",
  },
  {
    id: "atlas-nutrition",
    name: "Atlas Wellness Kitchen",
    type: "Nutrition coach",
    area: "Atlas",
    price: "650 ETB",
    bestFor: "Weight, energy, and fasting meal planning",
    category: "Food",
    emoji: "🍱",
    description: "Group nutrition coaching and meal planning workshops. Focuses on building sustainable eating habits using affordable local ingredients. Offers fasting-aware and budget meal plans.",
    rating: 4.6,
    reviews: 58,
    tags: ["group sessions", "fasting plans", "budget meals"],
    availableToday: true,
    slots: ["10:00 AM", "02:00 PM", "05:00 PM"],
    passportDiscount: 15,
    distance: "~25 min from Bole",
    hours: "Mon–Sat 9:00 AM – 7:00 PM",
    phone: "+251 91 901 2347",
  },
  {
    id: "mexico-counselor",
    name: "Mexico Wellness Counselor",
    type: "Therapist & counselor",
    area: "Mexico",
    price: "800 ETB",
    bestFor: "Burnout, anxiety, and emotional support",
    category: "Stress",
    emoji: "🧠",
    description: "Certified wellness counselor offering individual and couples sessions. Works with burnout, work-related stress, relationship challenges, and general emotional well-being. Sessions available in Amharic and English.",
    rating: 4.9,
    reviews: 47,
    tags: ["bilingual", "burnout", "anxiety", "private"],
    availableToday: false,
    slots: ["09:00 AM", "11:00 AM", "02:00 PM", "04:00 PM"],
    passportDiscount: 20,
    distance: "~22 min from Bole",
    hours: "Mon–Fri 8:00 AM – 6:00 PM",
    phone: "+251 91 012 3458",
  },
  {
    id: "kirkos-screening",
    name: "Kirkos Health Screening",
    type: "Health screening",
    area: "Kirkos",
    price: "300 ETB",
    bestFor: "BP check, glucose test, and lifestyle review",
    category: "Recovery",
    emoji: "🩺",
    description: "Comprehensive health screening for urban adults. Includes blood pressure measurement, fasting glucose test, BMI, and a 15-minute lifestyle review with a health professional. Results same day.",
    rating: 4.5,
    reviews: 134,
    tags: ["same day results", "BP check", "glucose test", "lifestyle review"],
    availableToday: true,
    slots: ["08:00 AM", "09:30 AM", "11:00 AM", "01:00 PM", "03:00 PM"],
    passportDiscount: 10,
    distance: "~30 min from Bole",
    hours: "Mon–Sat 7:30 AM – 5:00 PM",
    phone: "+251 91 123 4569",
  },
  {
    id: "tulsi-efoy-yoga",
    name: "Tulsi Efoy Yoga Reset",
    type: "Beginner yoga and breath",
    area: "Bole",
    price: "450 ETB",
    bestFor: "Stress, poor sleep, gentle alignment",
    category: "Stress",
    emoji: "Y",
    description: "A beginner-friendly breath, alignment, and relaxation session for people who need a gentle reset. Uses simple movement, shoulder release, and guided breathing in English and Amharic-ready formats.",
    rating: 4.8,
    reviews: 126,
    tags: ["beginner", "breath", "alignment", "bilingual"],
    availableToday: true,
    slots: ["07:30 AM", "12:30 PM", "06:30 PM"],
    passportDiscount: 15,
    distance: "~10 min from Bole Road",
    hours: "Mon-Sat 7:00 AM - 8:30 PM",
    phone: "+251 91 234 5688",
  },
  {
    id: "bole-spine-posture",
    name: "Bole Spine & Posture Desk",
    type: "Spine/posture assessment",
    area: "Bole",
    price: "650 ETB",
    bestFor: "Neck, shoulder, back, wrist, and sitting-related pain",
    category: "Movement",
    emoji: "S",
    description: "A posture and movement assessment for students and office workers. Screens for sitting load, neck and shoulder tension, wrist strain, and referral needs before suggesting safe mobility.",
    rating: 4.7,
    reviews: 98,
    tags: ["posture", "spine-safe", "office workers", "triage"],
    availableToday: true,
    slots: ["09:00 AM", "01:00 PM", "04:30 PM"],
    passportDiscount: 10,
    distance: "~12 min from Bole Road",
    hours: "Mon-Fri 8:00 AM - 6:00 PM, Sat 9:00 AM - 2:00 PM",
    phone: "+251 91 345 6799",
  },
  {
    id: "women-telehealth",
    name: "Private Women's Health Teleconsult",
    type: "Licensed teleconsult",
    area: "Online",
    price: "700 ETB",
    bestFor: "Cycle, pregnancy, postpartum, and severe cramp questions",
    category: "Recovery",
    emoji: "W",
    description: "A confidential teleconsult pathway for cycle, pregnancy, postpartum, cramps, and privacy-sensitive questions. Designed as a referral layer, not a replacement for emergency care.",
    rating: 4.9,
    reviews: 84,
    tags: ["private", "telehealth", "women's health", "licensed"],
    availableToday: true,
    slots: ["10:00 AM", "02:00 PM", "07:00 PM"],
    passportDiscount: 20,
    distance: "Online",
    hours: "Daily 8:00 AM - 9:00 PM",
    phone: "+251 91 456 7800",
  },
  {
    id: "kidi-mindfulness",
    name: "Body Wisdom Mindfulness Workshop",
    type: "Mindfulness workshop",
    area: "Kazanchis",
    price: "500 ETB",
    bestFor: "Body awareness, reflection, and stress regulation",
    category: "Stress",
    emoji: "M",
    description: "A practical mindfulness and reflection workshop that helps users listen to early body signals, journal safely, and build daily regulation practices alongside medical care.",
    rating: 4.8,
    reviews: 61,
    tags: ["body awareness", "reflection", "mindfulness", "workshop"],
    availableToday: false,
    slots: ["Wednesday 06:00 PM", "Saturday 10:00 AM"],
    passportDiscount: 15,
    distance: "~15 min from Meskel Square",
    hours: "Wed 6:00 PM, Sat 10:00 AM",
    phone: "+251 91 567 7811",
  },
];

export const wellnessPackages: WellnessPackage[] = [
  {
    id: "burnout-reset",
    title: "Burnout Reset Bundle",
    subtitle: "Yoga + Counseling + Massage",
    emoji: "🔄",
    providerIds: ["bole-yoga", "mexico-counselor", "lideta-massage"],
    providerNames: ["Bole Reset Yoga", "Mexico Counselor", "Lideta Spa"],
    originalEtb: 2050,
    discountPct: 18,
    finalEtb: 1681,
    bestFor: "Stress ≥ 7 or burnout signals",
  },
  {
    id: "active-start",
    title: "Active Start Package",
    subtitle: "Gym + Nutritionist + Walk Club",
    emoji: "⚡",
    providerIds: ["piazza-gym", "kazanchis-nutrition", "meskel-walk"],
    providerNames: ["Piazza Gym", "Kazanchis Nutrition", "Meskel Walk Club"],
    originalEtb: 900,
    discountPct: 12,
    finalEtb: 792,
    bestFor: "Low movement + food improvement",
  },
  {
    id: "full-wellness-day",
    title: "Full Wellness Day",
    subtitle: "Yoga + Spa + Screening",
    emoji: "🌟",
    providerIds: ["bole-yoga", "lideta-massage", "kirkos-screening"],
    providerNames: ["Bole Yoga", "Lideta Spa", "Kirkos Screening"],
    originalEtb: 1550,
    discountPct: 22,
    finalEtb: 1209,
    bestFor: "Complete reset — any score below 65",
  },
  {
    id: "clarity-pack",
    title: "Mind Clarity Pack",
    subtitle: "Meditation + Counseling",
    emoji: "🧘",
    providerIds: ["bole-meditation", "mexico-counselor"],
    providerNames: ["Bole Mindfulness", "Mexico Counselor"],
    originalEtb: 1080,
    discountPct: 14,
    finalEtb: 928,
    bestFor: "Anxiety, racing thoughts, or low mood",
  },
];
