import { Provider } from "./types";

export const providers: Provider[] = [
  {
    id: "bole-yoga",
    name: "Bole Reset Yoga",
    type: "Beginner yoga",
    area: "Bole",
    price: "350 ETB",
    bestFor: "High stress, low sleep",
    category: "Stress",
  },
  {
    id: "bole-meditation",
    name: "Bole Mindfulness Studio",
    type: "Guided meditation",
    area: "Bole",
    price: "280 ETB",
    bestFor: "Anxiety, burnout, and racing thoughts",
    category: "Stress",
  },
  {
    id: "lideta-massage",
    name: "Lideta Recovery Spa",
    type: "Massage",
    area: "Lideta",
    price: "900 ETB",
    bestFor: "Muscle tension and burnout",
    category: "Recovery",
  },
  {
    id: "entoto-retreat",
    name: "Entoto Weekend Reset",
    type: "Wellness retreat",
    area: "Entoto",
    price: "1,800 ETB",
    bestFor: "Sleep debt and social reset",
    category: "Recovery",
  },
  {
    id: "meskel-walk",
    name: "Meskel Walk Club",
    type: "Guided group walk",
    area: "Meskel Square",
    price: "Free",
    bestFor: "Low movement days",
    category: "Movement",
  },
  {
    id: "piazza-gym",
    name: "Piazza Fitness Center",
    type: "Gym",
    area: "Piazza",
    price: "400 ETB / month",
    bestFor: "Building consistent movement habits",
    category: "Movement",
  },
  {
    id: "kazanchis-nutrition",
    name: "Kazanchis Nutrition Desk",
    type: "Nutritionist",
    area: "Kazanchis",
    price: "500 ETB",
    bestFor: "BP and glucose lifestyle habits",
    category: "Food",
  },
  {
    id: "atlas-nutrition",
    name: "Atlas Wellness Kitchen",
    type: "Nutrition coach",
    area: "Atlas",
    price: "650 ETB",
    bestFor: "Weight, energy, and fasting meal planning",
    category: "Food",
  },
  {
    id: "mexico-counselor",
    name: "Mexico Wellness Counselor",
    type: "Therapist / counselor",
    area: "Mexico",
    price: "800 ETB",
    bestFor: "Burnout, anxiety, and emotional support",
    category: "Stress",
  },
  {
    id: "kirkos-screening",
    name: "Kirkos Health Screening",
    type: "Health screening",
    area: "Kirkos",
    price: "300 ETB",
    bestFor: "BP check, glucose test, and lifestyle review",
    category: "Recovery",
  },
  {
    id: "tulsi-efoy-yoga",
    name: "Tulsi Efoy Yoga Reset",
    type: "Beginner yoga and breath",
    area: "Bole",
    price: "450 ETB",
    bestFor: "Stress, poor sleep, gentle alignment",
    category: "Stress",
  },
  {
    id: "bole-spine-posture",
    name: "Bole Spine & Posture Desk",
    type: "Spine/posture assessment",
    area: "Bole",
    price: "650 ETB",
    bestFor: "Neck, shoulder, back, wrist, and sitting-related pain",
    category: "Movement",
  },
  {
    id: "women-telehealth",
    name: "Private Women's Health Teleconsult",
    type: "Licensed teleconsult",
    area: "Online",
    price: "700 ETB",
    bestFor: "Cycle, pregnancy, postpartum, and severe cramp questions",
    category: "Recovery",
  },
  {
    id: "kidi-mindfulness",
    name: "Body Wisdom Mindfulness Workshop",
    type: "Mindfulness workshop",
    area: "Kazanchis",
    price: "500 ETB",
    bestFor: "Body awareness, reflection, and stress regulation",
    category: "Stress",
  },
];
