import nodemailer from "nodemailer";

type SendAuthCodeInput = {
  email: string;
  code: string;
  mode: "login" | "signup";
  name?: string | null;
};

function smtpConfigured() {
  return Boolean(process.env.SMTP_HOST);
}

function createTransport() {
  if (!smtpConfigured()) {
    return nodemailer.createTransport({ jsonTransport: true });
  }

  const port = Number(process.env.SMTP_PORT || 587);

  return nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port,
    secure: process.env.SMTP_SECURE === "true" || port === 465,
    connectionTimeout: Number(process.env.SMTP_CONNECTION_TIMEOUT_MS || 8000),
    greetingTimeout: Number(process.env.SMTP_GREETING_TIMEOUT_MS || 8000),
    socketTimeout: Number(process.env.SMTP_SOCKET_TIMEOUT_MS || 12000),
    auth:
      process.env.SMTP_USER && process.env.SMTP_PASS
        ? {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
          }
        : undefined,
  });
}

export async function sendAuthCodeEmail({
  email,
  code,
  mode,
  name,
}: SendAuthCodeInput) {
  const transport = createTransport();
  const firstName = name?.trim().split(/\s+/)[0] || "there";
  const appUrl = process.env.APP_URL || "http://localhost:3000";
  const subject =
    mode === "signup" ? "Confirm your TenaLoop account" : "Your TenaLoop login code";

  const text = [
    `Hi ${firstName},`,
    "",
    `Your TenaLoop 360 ${mode === "signup" ? "signup" : "login"} code is ${code}.`,
    "It expires soon, so use it in the browser window that requested it.",
    "",
    `Open TenaLoop: ${appUrl}`,
    "",
    "If you did not request this code, you can ignore this email.",
  ].join("\n");

  const info = await transport.sendMail({
    to: email,
    from: process.env.SMTP_FROM || "TenaLoop 360 <no-reply@tenaloop.local>",
    subject,
    text,
  }).catch((error: unknown) => {
    const message = error instanceof Error ? error.message : "SMTP delivery failed.";
    throw new Error(`Auth email could not be sent through SMTP. ${message}`);
  });

  if (!smtpConfigured()) {
    console.info(
      "TenaLoop auth email generated by Nodemailer:",
      (info as { message?: string }).message || JSON.stringify(info),
    );
  }

  return {
    delivery: smtpConfigured() ? "smtp" : "console",
  };
}
